name: 'pr-markdownlint'

on:
  pull_request:
    paths: ['**/*.md']

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: npx markdownlint-cli "**/*.md" --ignore "docs/index.md" --fix
      - uses: googleapis/code-suggester@v5
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: review
          pull_number: ${{ github.event.pull_request.number }}
          git_dir: '.'
